site_name: Inconceivable Documentation
site_url: https://team2530.github.io/Documentation/

repo_url: https://github.com/Team2530/Documentation
edit_uri: https://github.dev/Team2530/Documentation/blob/master/docs/

theme: 
  name: material
  custom_dir: docs
  palette:
    scheme: default
    primary: custom
    accent: custom
  font:
    text: Roboto
  logo: assets/logo.svg # TODO: This logo is the wrong color
  favicon: assets/favicon.ico
  icon:
    repo: material/brands/github
    edit: material/pencil
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.prune
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.action.edit
    - toc.follow
extra:
  tags:
    Programming: computer
    Electronics: bolt
    CAD: rainy
    Strategy: strategy
    Machining: tools_power_drill
extra_css:
  - style.css
plugins:
  - search
  - tags
  - ezlinks
  - backlinks_section
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
