site_name: Inconceivable Documentation
theme: 
  name: material
  palette:
    scheme: default
    primary: custom
    accent: custom
  font:
    text: Roboto
  logo: assets/logo.svg # TODO: This logo is the wrong color
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.top
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.select
extra_css:
  - style.css
plugins:
  - search
  - tags
  - ezlinks
markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
